### ISSUE TITLE
IdeaMantis not working in phpstorm 2018.3 mantisBT 2.15

### ISSUE THREAD

**Issue by bestbean** [domjos1994/ideaMantis#10]
No login possible to MantisBT, since MantisBT uses new login dialog.
Click on "Show Mantis-BT issues" freezes PhpStorm

**Comment by domjos1994** [comment]
Did you already add your credentials in the Settings-Screen?

**Comment by bestbean** [comment]
Yes.
Error message when trying loging in settings screen:
Request failed. Reason: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

**Comment by domjos1994** [comment]
Which version of MantisBT do you use?

**Comment by bestbean** [comment]
mantisBT 2.15 as mentioned in issue title.

**Comment by mmkulikov** [comment]
Last version PhpStorm/ Don`t connect
![image](https://user-images.githubusercontent.com/4347816/54882976-3a182a80-4e60-11e9-934e-f195e2051348.png)

**Comment by domjos1994** [comment]
Did you enable soap-extension in the php.ini?

**Comment by mmkulikov** [comment]
> Did you enable soap-extension in the php.ini?

This plugin required PHP? Im work in windows phpstorm...

**Comment by domjos1994** [comment]
The Plugin doesn't require PHP, but you need to enable Soap on the Server where MantisBT is installed.
What do you see, when you follow the link:
[URL to MantisBT]/api/soap/mantisconnect.php?wsdl?

**Comment by mmkulikov** [comment]
> The Plugin doesn't require PHP, but you need to enable Soap on the Server where MantisBT is installed. What do you see, when you follow the link: [URL to MantisBT]/api/soap/mantisconnect.php?wsdl?

jetbrains task plugin work correct and login witout any problem
![image](https://user-images.githubusercontent.com/4347816/54935230-2c29de80-4f20-11e9-864f-090e29832f7e.png)

**Comment by grv87** [comment]
The similar problem with IDEA Community Edition 2019.2.
Connection tested successfully, but IDE restart frozes on "Preparing workspace..." or "Reopening files..."

**Comment by bestbean** [comment]
Problem still exists.
PhpStorm 2020.1
Functional soap extension on server where MantisBT is installed.

[URL to MantisBT]/api/soap/mantisconnect.php?wsdl?
`Web Service: MantisConnect
Target Namespace:
http://futureware.biz/mantisconnect
Port MantisConnectPort Port typeSource code
Location:
https://xxx/api/soap/mantisconnect.php
Protocol:
SOAP
Default style:
rpc
Transport protocol:
SOAP over HTTP
Operations:
etc`
