### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by lcsqlpete** [domjos1994/ideaMantis#14]
Just downloaded and installed into PHPStorm 2020.2 and restarted.  I completed the connection details for Mantis and got a success message.

NOne of the PHPSTorm menus include anything to do with Mantis or the plugin so how do I see Mantis bugs from the IDE?

**Comment by domjos1994** [comment]
Include the Toolwindow of IdeaMantis.

Am 14. November 2020 22:41:37 MEZ schrieb lcsqlpete <notifications@github.com>:
>Just downloaded and installed into PHPStorm 2020.2 and restarted.  I
>completed the connection details for Mantis and got a success message.
>
>NOne of the PHPSTorm menus include anything to do with Mantis or the
>plugin so how do I see Mantis bugs from the IDE?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domjos1994/ideaMantis/issues/14

-- Gesendte von /e/ Mail.

**Comment by lcsqlpete** [comment]
Sorry, I don't understand. Could you please explain in detail.

Pete
lcSQL Software

**Comment by domjos1994** [comment]
I will make a wiki
