### ISSUE TITLE
PHPStorm Support

### ISSUE THREAD

**Issue by upjersdave** [domjos1994/ideaMantis#2]
Hi there,

We thought we would try and install this in PHPStorm, which is based on IntelliJ, but the menus don't appear as they do in IntelliJ-Idea. Would it be an easy fix to add support so they appear in PHPStorm too? We have two developers here who are dying to use it.

We tested in PhpStorm 2016.3.2.

Thanks!

**Comment by upjersdave** [comment]
We had a fiddle and manage to fix it ourselves by adding a dependency tag to the plugin xml.
https://github.com/domjos1994/ideaMantis/pull/3

**Comment by domjos1994** [comment]
Thanks

**Comment by upjersdave** [comment]
Thanks!

We've had a chance to test the module a little more, and find that we are unable to edit issues within PHPStorm (we can list them and add them, but all the edit fields are greyed out). We also don't see the "Edit' or "Delete" fields, like in the screenshot. Is this normal, or is it a known bug?

The user-permissions for our Mantis accounts allow for editing of an issue, but not for deleting, but I assume that isn't a problem.

**Comment by domjos1994** [comment]
Hallo,

this is a new bug.
I will try to fix it in the evening. 

Am 17. Mai 2017 08:28:29 MESZ schrieb upjersdave <notifications@github.com>:
>Thanks!
>
>We've had a chance to test the module a little more, and find that we
>are unable to edit issues within PHPStorm (we can list them and add
>them, but all the edit fields are greyed out). We also don't see the
>"Edit' or "Delete" fields, like in the screenshot. Is this normal, or
>is it a known bug?
>
>The user-permissions for our Mantis accounts allow for editing of an
>issue, but not for deleting, but I assume that isn't a problem.
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/domjos1994/ideaMantis/issues/2#issuecomment-301998102

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by domjos1994** [comment]
What Access-Level do you have?
Dominic Joas

**Comment by upjersdave** [comment]
Our mantis is in German, but:

Access Level (I think this is the correct translation): **Reporter**
Project Level: **Entwickler**

**Comment by upjersdave** [comment]
We just switched both access levels to **Developer** (Entwickler) and it now works.

Thanks for the help!

**Comment by domjos1994** [comment]
I have found the bug.
The plugin checks the access-level of the user, but not the access-level, which the user has for the project.

In the next version the problem will be solved.

**Comment by upjersdave** [comment]
Cool. Thanks :-)

**Comment by domjos1994** [comment]
If you got further questions feel free to message me.

**Comment by upjersdave** [comment]
Thank you! We'll check out the new version :-)

p.s. Are you interested in feature requests?

**Comment by domjos1994** [comment]
Yes, of course :D

**Comment by upjersdave** [comment]
I'll open a new ticket :-)

**Comment by upjersdave** [comment]
https://github.com/domjos1994/ideaMantis/issues/5
