### ISSUE TITLE
Mantis at different URL can't connect.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [domjos1994/ideaMantis#4]
Hi is it possible to connect when the hostname is a url like so?

> https://www.domain.co.nz/support/tickets/

Actually on second thought, I'm trying to connect from PHPStorm so it might be caused by #3 rather than the URL being a different location.

**Comment by domjos1994** [comment]
Have you tried the url without the slash at the end?

Do you see a list of projects?

**Comment by LiamKarlMitchell** [comment]
Yeah, its got a list of projects now thanks.
