### ISSUE TITLE
Idea: Create tickets via comments

### ISSUE THREAD

**Issue by upjersdave** [domjos1994/ideaMantis#5]
I often write TODOs in my code (inside of Docblocks) as a reminder that I need to do something in future. For example;

``` php
<?php
class VeryRandomTools
{
    /**
     * @TODO: Reimplement getRandomNumber so that it actually returns a random number.
     */
	public function getRandomNumber()
	{
		return 42;
	}
}
```

At the moment, if I want to add this to Mantis as a ticket, I would have to copy the text, open the mantis window, click new, paste etc. etc. (which is long winded), and thought up another solution:

Would it be possible, when the cursor is over the word "TODO", to somehow add a keyboard-shortcut, for example, `ALT-Enter`, which would then offer to add any remaining text on that line automatically to Mantis as a new ticket? Upon creation, it could even replace the text in the comment with something like this:

``` php
<?php
class VeryRandomTools
{
    /**
     * @TODO: MANTIS#88613 - Reimplement getRandomNumber so that it actually returns a random number.
     */
	public function getRandomNumber()
	{
		return 42;
	}
}
```

..and `88613` could even be clickable and open Mantis in the browser or Mantis-Window.

One could even consider adding other keyboard shortcuts for automatically closing or commenting on tickets.. 

What do you think?

**Comment by domjos1994** [comment]
I think, it will be possible to add these features, but I can't promise it.

I will research into it.

**Comment by domjos1994** [comment]
I've made a research. It is possible. There will be a new entry in the context-menu which you can call with a shortcut.

I will introduce the feature in the new version.
