### ISSUE TITLE
Unable to connect from PHPStorm 2017.2

### ISSUE THREAD

**Issue by grumpy-gnome** [domjos1994/ideaMantis#6]
Trying to set up my issues link from my shiny new PHPStorm install. Can't get the connection to work, nor do I see any meaningful errors. If I open the issues window, I get the message "Wrong settings!: The connection-settings are incorrect!" but no detail.  
![capture](https://user-images.githubusercontent.com/33554688/32672245-40a01202-c642-11e7-91f7-3392a4878450.PNG)
A screengrab of my settings is attached.
I'm hoping I'm just doing something trivially wrong! Any help would be appreciated.

**Comment by domjos1994** [comment]
Good Evening,
are you sure your Login-Data are correct?
Did you press the Button "Test Connection"?
Which Version of MantisBT do you use?

**Comment by grumpy-gnome** [comment]
Hi, thanks for coming back so quickly. 

I have double checked the logon details and the test connection button doesn't seem to do very much. There is no error in the event log. I'm using Mantisbt 2.6.0 schema 209.

**Comment by domjos1994** [comment]
Did you enable Soap in your PHP-Configuration?

**Comment by grumpy-gnome** [comment]
Hi, yep I double checked and SOAP is enabled. Would it help you diagnose if you had a logon to try? There is nothing very sensitive if you wanted to have access to see what might be causing the problem. I have also noticed that if I try and "test connection" a couple of times, it causes PHPStorm to hang to the extent that I have to terminate the process with Task Manager!

**Comment by grumpy-gnome** [comment]
Oops pressed wrong button...

**Comment by domjos1994** [comment]
Good evening,
yes it would help, if I had a logon.
I noticed that the Soap Api in your Mantis doesn't right work.
https://mantis.jwdarcy.com/api/soap/mantisconnect.php?wsdl

**Comment by grumpy-gnome** [comment]
Thanks for your support - I do hope it's not just a config thing on my webhost, it would be really useful to use this plugin! Anyway, user details sent to you...

**Comment by domjos1994** [comment]
There is no access to soap api of MantisBT.
Did you delete it?

**Comment by grumpy-gnome** [comment]
Er not knowingly!

 

I’m beginning to think I have some bad install. I’ll install the latest version over the next few days and try again. I’ll post an update on the thread when I’ve done this.

 

Thanks for your patience.

 

Chris

**Comment by grumpy-gnome** [comment]
Reinstalled mantisbt and all is now working! Yay! Thanks so much for your support and my apologies for not doing this straightaway.
Many thanks

**Comment by domjos1994** [comment]
You're welcome!
If you've got ideas for new features or a new Plugin, 
let me know.
