### ISSUE TITLE
HTML codierte Url bei öffnen eines Attachments

### ISSUE THREAD

**Issue by SevenbitsIt** [domjos1994/ideaMantis#7]
Wenn man aus dem Pluginfenster ein Attachment für einen Bug öffnen möchte wird die Url folgendermaßen generiert:

https://ssl.example.com/zf/public/mantis/file_download.php?file_id=78&amp;type=bug
statt:
https://ssl.example.com/zf/public/mantis/file_download.php?file_id=78&type=bug

**Comment by domjos1994** [comment]
Guten Abend,
brauchst du die Änderung schnell?
Ich hab das Problem mit dem letzten Commit bereits behoben und würde das Problem mit dem nächsten Update lösen.

**Comment by SevenbitsIt** [comment]
Nein reicht beim nächsten Update. Danke dir!

**Comment by domjos1994** [comment]
Sehr geehrte Damen und Herren,

danke für Ihre Anfrage.
Ich versuche mich so schnell wie möglich um Ihr Anliegen zu kümmern.


Mit freundlichen Grüßen

Dominic Joas
