### ISSUE TITLE
selectable texts

### ISSUE THREAD

**Issue by ms502040** [domjos1994/ideaMantis#8]
Hi,
make all texts in bugreport selectable even if not editing it (unable to copy - paste without push edit button)

**Comment by domjos1994** [comment]
Add Fast-Track-Mode in new version

**Comment by ms502040** [comment]
great, thx :)

**Comment by domjos1994** [comment]
Sehr geehrte Damen und Herren,

danke für Ihre Anfrage.
Ich versuche mich so schnell wie möglich um Ihr Anliegen zu kümmern.


Mit freundlichen Grüßen

Dominic Joas
