### ISSUE TITLE
Converting TODO to ticket - File Attachments

### ISSUE THREAD

**Issue by upjersdave** [domjos1994/ideaMantis#9]
Hi,

We use this plugin quite extensively to convert comments/todos into mantis tickets. One thing that is quite annoying is that the "Mark text as bug" and the "Mark todo as bug" windows automatically add the current file as an attachment. Is there any way to deactivate this? 

![grafik](https://user-images.githubusercontent.com/22983375/39814918-8a87c6e4-5396-11e8-8c9a-76bdef057991.png)

We're using PHPStorm

Thanks and regards

Dave

**Comment by domjos1994** [comment]
Hello,
currently there isn't a way to do that, but I will include that feature in the next version.

Best regards
Dominic

**Comment by upjersdave** [comment]
!!  Super !! Thank you 👍
